# Generated by Django 3.2.9 on 2022-01-11 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='producent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.producent'),
        ),
        migrations.AlterUniqueTogether(
            name='zamowienie',
            unique_together={('id_zamowienie', 'klient', 'producent')},
        ),
    ]
