# Generated by Django 3.2.9 on 2021-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
