# Generated by Django 3.2.9 on 2021-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiadomosc',
            name='id_wiadomosc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='wiadomosc',
            unique_together={('id_wiadomosc', 'czat')},
        ),
    ]
