# Generated by Django 3.2.9 on 2021-11-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211128_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czat',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.klient'),
        ),
        migrations.AlterField(
            model_name='czat',
            name='producent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producent'),
        ),
    ]
