# Generated by Django 3.2.9 on 2022-01-11 19:32

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220111_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='id_zamowienie',
            field=models.IntegerField(default=shop.models.add_one_zamowienie, null=True),
        ),
    ]
