# Generated by Django 3.2.9 on 2021-11-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211128_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='id_zamowienie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='zamowienie',
            unique_together={('id_zamowienie', 'klient')},
        ),
    ]
