# Generated by Django 3.2.9 on 2022-01-26 21:55

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_kategoria_id_nadkategorii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='id_produktu',
            field=models.AutoField(default=shop.models.add_one_produkt, primary_key=True, serialize=False),
        ),
    ]
