# Generated by Django 3.2.9 on 2021-11-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211128_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='producent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.producent'),
        ),
    ]
