# Generated by Django 3.2.9 on 2021-11-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_zamowienie_producent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zamowienie',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='zamowienie',
            constraint=models.UniqueConstraint(fields=('id_zamowienie', 'klient'), name='id_zamowienie_klient'),
        ),
    ]
