# Generated by Django 3.2.9 on 2021-11-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211128_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.klient'),
        ),
    ]
