# Generated by Django 3.2.9 on 2021-11-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211128_1105'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zamowienie',
            name='id_zamowienie_klient',
        ),
        migrations.AlterUniqueTogether(
            name='zamowienie',
            unique_together={('id_zamowienie', 'klient')},
        ),
    ]
